<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_ion-more</name>
   <tag></tag>
   <elementGuidId>e037976a-3fa6-432c-93aa-5a069fd8cb02</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ion-more</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-container&quot;)/div[@class=&quot;scroll-y&quot;]/div[@class=&quot;graph-list-header&quot;]/div[@class=&quot;relative resource-toolbar&quot;]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-primary dropdown-toggle&quot;]/i[@class=&quot;ion-more&quot;]</value>
   </webElementProperties>
</WebElementEntity>
